language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
solution: KloudCodingChallenge.sln
script:
  - cd KloudCodingChallenge
  - dotnet restore
  - dotnet build
  - dotnet test KloudCodingChallenge.Test/KloudCodingChallenge.Test.csproj
deploy:
  provider: azure_web_apps
notifications:
  email:
    - lingalamanojreddy@outlook.com